### ISSUE TITLE
implement compression

### ISSUE THREAD

**Issue by bendichter** [schnitzer-lab/nwb_schnitzer_lab#3]
Use the new DataPipe object to write data with compression. This requires you to write the data pipe without data, load the file back in, and append to it with the append method. See the test [here](https://github.com/NeurodataWithoutBorders/matnwb/blob/16729c2cbc1c46189c896d6e12d2f7705a721e69/%2Btests/%2Bunit/dataPipeTest.m)

**Comment by bendichter** [comment]
See [this open issue](https://github.com/NeurodataWithoutBorders/matnwb/issues/184) for the plan for an improved workflow

**Comment by bahanonu** [comment]
https://github.com/NeurodataWithoutBorders/matnwb/issues/184.
